DATABASE:
  DRIVER: postgres
  HOST: localhost
  PORT: 5432
  NAME: youtuber
  USERNAME: youtuber
  PASSWORD: youtuber
  QUERY: sslmode=disable&timezone=UTC
  MAX_IDLE_CONNECTIONS: 2
  MAX_OPEN_CONNECTIONS: 50
  CONN_MAX_LIFETIME_MIN: 10
  CONN_MAX_IDLE_TIME: 3000
  MIGRATION:
    PATH: TBA
SERVER:
  PORT: 8080
  READ_TIMEOUT_MS: 20000
  WRITE_TIMEOUT_MS: 15000
  GRACEFUL_SHUTDOWN_TIMEOUT_MS: 20000
WORKER:
  REDIS:
    ADDRESS: localhost:6379
  CONCURRENCY: 30
  JOB_RETRY_MAX_COUNT: 5
REDIS:
  ADDRESS: "localhost:6379"
  USER: default
  PASSWORD: ''
YOUTUBE:
  HOST: "https://youtube.googleapis.com"
  AUTHKEY: replace-with-auth-key
